# Generated by Django 4.2.4 on 2023-12-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0003_review_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_agent',
            name='login',
        ),
        migrations.AddField(
            model_name='delivery_agent',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fapp.restaurant'),
            preserve_default=False,
        ),
    ]
