# Generated by Django 4.2.4 on 2023-12-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0004_remove_delivery_agent_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_agent',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fapp.login_table'),
            preserve_default=False,
        ),
    ]
