# Generated by Django 4.2.4 on 2023-12-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_delivery_agent_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='payment',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.user')),
            ],
        ),
    ]
