# Generated by Django 3.2.24 on 2024-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_timeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
